export const demoFormMessages = {
  ru: {
    title: 'Запросить демо',
    subtitle: 'Оставьте контакты, и мы покажем PhishLake на сценарии вашей команды.',
    fields: {
      name: 'Имя',
      company: 'Компания',
      email: 'Рабочий email',
      phone: 'Телефон',
      message: 'Что хотите проверить',
    },
    placeholders: {
      name: 'Алексей С.',
      company: 'Название компании',
      email: 'name@company.kz',
      phone: '+7',
      message: 'Например: пилот на IT или HR отдел',
    },
    submit: 'Отправить заявку',
    close: 'Закрыть форму',
    successTitle: 'Заявка принята',
    successText: 'Мы свяжемся с вами и договоримся о коротком демо.',
  },
  kk: {
    title: 'Демо сұрау',
    subtitle: 'Байланыс деректерін қалдырыңыз, PhishLake платформасын командаңыздың сценарийінде көрсетеміз.',
    fields: {
      name: 'Аты-жөні',
      company: 'Компания',
      email: 'Жұмыс email',
      phone: 'Телефон',
      message: 'Нені тексергіңіз келеді',
    },
    placeholders: {
      name: 'Алексей С.',
      company: 'Компания атауы',
      email: 'name@company.kz',
      phone: '+7',
      message: 'Мысалы: IT немесе HR бөліміне пилот',
    },
    submit: 'Өтінім жіберу',
    close: 'Форманы жабу',
    successTitle: 'Өтінім қабылданды',
    successText: 'Біз сізбен байланысып, қысқа демо уақытын келісеміз.',
  },
  en: {
    title: 'Request a demo',
    subtitle: 'Leave your details and we will show PhishLake using your team scenario.',
    fields: {
      name: 'Name',
      company: 'Company',
      email: 'Work email',
      phone: 'Phone',
      message: 'What you want to test',
    },
    placeholders: {
      name: 'Alex S.',
      company: 'Company name',
      email: 'name@company.kz',
      phone: '+7',
      message: 'For example: pilot for IT or HR',
    },
    submit: 'Send request',
    close: 'Close form',
    successTitle: 'Request received',
    successText: 'We will contact you and schedule a short demo.',
  },
};
