export const howItWorksMessages = {
  ru: {
    kicker: 'Как работает',
    title: 'От первой симуляции до измеримого снижения риска',
    subtitle:
      'Полный цикл работы с человеческим фактором. Мы помогаем выявить уязвимости, обучить сотрудников и показать руководству измеримый результат.',
    modalEyebrow: 'Recreated UI',
    closeLabel: 'Закрыть',
    actionDone: 'Готово',
    recreated: {
      campaign: {
        tabs: ['Готовый сценарий', 'Только письмо', 'QR-атака'],
        field: 'Название кампании',
        value: 'Microsoft 365: обновление пароля',
        scenario: 'Корпоративный портал',
        chain: 'Письмо → посадочная → урок → тест',
        template: 'Шаблон письма',
        templateMeta: 'IT Support · высокий риск · средний click-rate 18%',
      },
      risk: {
        opened: 'Открытия',
        clicks: 'Клики',
        credentials: 'Ввод данных',
        openedSub: '154 из 1 243',
        clicksSub: '70 из 1 243',
        credentialsSub: '22 сотрудника',
        events: ['opened → clicked', 'clicked → credentials', 'opened'],
      },
      training: {
        title: 'Персональное обучение',
        desc: 'Автоматически назначается сотрудникам с кликом или вводом данных.',
        lesson: 'Как распознать поддельный Microsoft 365',
        meta: '7 минут · тест из 5 вопросов',
        statuses: ['Назначено', 'В процессе', 'Завершено'],
      },
      report: {
        riskScore: 'Risk score',
        reduction: '-35% после повторной симуляции',
        files: ['Executive summary.pdf', 'Отчет по подразделениям.xlsx'],
      },
    },
    steps: [
      {
        title: 'Проводим симуляцию',
        text: 'Создаем реалистичные фишинговые письма и запускаем кампании за минуты.',
        visualTitle: 'Конструктор кампании',
        visualType: 'campaign',
        previewAction: 'Открыть визард',
        modalTitle: 'Запуск фишинговой симуляции',
        actionLabel: 'Запустить кампанию',
      },
      {
        title: 'Измеряем риск',
        text: 'Фиксируем клики и действия сотрудников, рассчитываем уровень риска.',
        visualTitle: 'Карта риска',
        visualType: 'risk',
        previewAction: 'Открыть аналитику',
        modalTitle: 'Измерение риска кампании',
        actionLabel: 'Показать события',
      },
      {
        title: 'Обучаем автоматически',
        text: 'Подключаем к обучению тех, кто попался, без лишнего шума для всей команды.',
        visualTitle: 'Назначение обучения',
        visualType: 'training',
        previewAction: 'Открыть назначение',
        modalTitle: 'Автоматическое обучение сотрудников',
        actionLabel: 'Назначить обучение',
      },
      {
        title: 'Анализируем результат',
        text: 'Отслеживаем прогресс и снижение риска в динамике.',
        visualTitle: 'Отчет для руководства',
        visualType: 'report',
        previewAction: 'Открыть отчет',
        modalTitle: 'Отчет о снижении риска',
        actionLabel: 'Сформировать отчет',
      },
    ],
  },
  kk: {
    kicker: 'Қалай жұмыс істейді',
    title: 'Бірінші симуляциядан тәуекелдің өлшенетін төмендеуіне дейін',
    subtitle:
      'Адам факторымен жұмыс істеудің толық циклі. Біз осалдықтарды табуға, қызметкерлерді оқытуға және басшылыққа өлшенетін нәтиже көрсетуге көмектесеміз.',
    modalEyebrow: 'Recreated UI',
    closeLabel: 'Жабу',
    actionDone: 'Дайын',
    recreated: {
      campaign: {
        tabs: ['Дайын сценарий', 'Тек хат', 'QR-шабуыл'],
        field: 'Кампания атауы',
        value: 'Microsoft 365: құпиясөзді жаңарту',
        scenario: 'Корпоративтік портал',
        chain: 'Хат → бет → сабақ → тест',
        template: 'Хат шаблоны',
        templateMeta: 'IT Support · жоғары тәуекел · орташа click-rate 18%',
      },
      risk: {
        opened: 'Ашулар',
        clicks: 'Кликтер',
        credentials: 'Дерек енгізу',
        openedSub: '1 243 ішінен 154',
        clicksSub: '1 243 ішінен 70',
        credentialsSub: '22 қызметкер',
        events: ['opened → clicked', 'clicked → credentials', 'opened'],
      },
      training: {
        title: 'Жеке оқыту',
        desc: 'Клик жасаған немесе дерек енгізген қызметкерлерге автоматты түрде тағайындалады.',
        lesson: 'Жалған Microsoft 365 хабарламасын қалай тануға болады',
        meta: '7 минут · 5 сұрақтық тест',
        statuses: ['тағайындалды', 'орындалуда', 'аяқталды'],
      },
      report: {
        riskScore: 'Risk score',
        reduction: '-35% қайталама симуляциядан кейін',
        files: ['Executive summary.pdf', 'Бөлімдер бойынша есеп.xlsx'],
      },
    },
    steps: [
      {
        title: 'Симуляция өткіземіз',
        text: 'Шынайы фишинг хаттарын жасап, кампанияларды бірнеше минутта іске қосамыз.',
        visualTitle: 'Кампания құрастыру',
        visualType: 'campaign',
        previewAction: 'Визардты ашу',
        modalTitle: 'Фишинг симуляциясын іске қосу',
        actionLabel: 'Кампанияны іске қосу',
      },
      {
        title: 'Тәуекелді өлшейміз',
        text: 'Қызметкерлердің кликтері мен әрекеттерін тіркеп, тәуекел деңгейін есептейміз.',
        visualTitle: 'Тәуекел картасы',
        visualType: 'risk',
        previewAction: 'Аналитиканы ашу',
        modalTitle: 'Кампания тәуекелін өлшеу',
        actionLabel: 'Оқиғаларды көрсету',
      },
      {
        title: 'Автоматты түрде оқытамыз',
        text: 'Қателескен қызметкерлерді бүкіл командаға шу шығармай жеке оқытуға қосамыз.',
        visualTitle: 'Оқытуды тағайындау',
        visualType: 'training',
        previewAction: 'Тағайындауды ашу',
        modalTitle: 'Қызметкерлерді автоматты оқыту',
        actionLabel: 'Оқытуды тағайындау',
      },
      {
        title: 'Нәтижені талдаймыз',
        text: 'Прогресті және тәуекелдің төмендеуін динамикада бақылап отырамыз.',
        visualTitle: 'Басшылыққа арналған есеп',
        visualType: 'report',
        previewAction: 'Есепті ашу',
        modalTitle: 'Тәуекелдің төмендеуі туралы есеп',
        actionLabel: 'Есепті қалыптастыру',
      },
    ],
  },
  en: {
    kicker: 'How it works',
    title: 'From the first simulation to measurable risk reduction',
    subtitle:
      'A complete cycle for working with human risk. We help identify vulnerabilities, train employees, and show leadership a measurable result.',
    modalEyebrow: 'Recreated UI',
    closeLabel: 'Close',
    actionDone: 'Done',
    recreated: {
      campaign: {
        tabs: ['Ready scenario', 'Email only', 'QR attack'],
        field: 'Campaign name',
        value: 'Microsoft 365: password update',
        scenario: 'Corporate portal',
        chain: 'Email → landing → lesson → test',
        template: 'Email template',
        templateMeta: 'IT Support · high risk · average click-rate 18%',
      },
      risk: {
        opened: 'Opened',
        clicks: 'Clicks',
        credentials: 'Data entered',
        openedSub: '154 of 1,243',
        clicksSub: '70 of 1,243',
        credentialsSub: '22 employees',
        events: ['opened → clicked', 'clicked → credentials', 'opened'],
      },
      training: {
        title: 'Personal training',
        desc: 'Automatically assigned to employees who clicked or entered data.',
        lesson: 'How to recognize a fake Microsoft 365 message',
        meta: '7 minutes · 5-question test',
        statuses: ['assigned', 'in progress', 'completed'],
      },
      report: {
        riskScore: 'Risk score',
        reduction: '-35% after repeat simulation',
        files: ['Executive summary.pdf', 'Department report.xlsx'],
      },
    },
    steps: [
      {
        title: 'Run a simulation',
        text: 'Create realistic phishing emails and launch campaigns in minutes.',
        visualTitle: 'Campaign builder',
        visualType: 'campaign',
        previewAction: 'Open wizard',
        modalTitle: 'Launch phishing simulation',
        actionLabel: 'Launch campaign',
      },
      {
        title: 'Measure risk',
        text: 'Capture employee clicks and actions, then calculate the risk level.',
        visualTitle: 'Risk map',
        visualType: 'risk',
        previewAction: 'Open analytics',
        modalTitle: 'Campaign risk measurement',
        actionLabel: 'Show events',
      },
      {
        title: 'Train automatically',
        text: 'Route employees who failed into focused training without extra noise for the whole team.',
        visualTitle: 'Training assignment',
        visualType: 'training',
        previewAction: 'Open assignment',
        modalTitle: 'Automatic employee training',
        actionLabel: 'Assign training',
      },
      {
        title: 'Analyze the result',
        text: 'Track progress and risk reduction over time.',
        visualTitle: 'Leadership report',
        visualType: 'report',
        previewAction: 'Open report',
        modalTitle: 'Risk reduction report',
        actionLabel: 'Generate report',
      },
    ],
  },
};
